language: objective-c
osx_image: xcode9.3

script:
  - xcodebuild -version
  - xcodebuild 
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.3' 
    -project SwiftDI.xcodeproj 
    -scheme SwiftDI 
    test