language: objective-c
osx_image: xcode8.3

script:
  - xcodebuild -version
  - xcodebuild
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME-$SCHEME"
    -sdk iphonesimulator11.3
    test


